implemented wp http api instead of curl
BananaCrystal/bananacrystal-payment-gateway pull request #13
Opened 2023-01-19 18:09 UTC by armansheikh

2023-01-19 18:54 UTC, esthervillars requested changes

2023-01-19 18:54 UTC, esthervillars commented on includes/class-banana-crystal-woocommerce.php
> +		);
@armansheikh can you set ssl_verify to true

2023-01-20 16:21 UTC, armansheikh commented on cron.php
> +        ),
@esthervillars  I didn't find any method to turn off logs. since cron is not part of woocommerce logs the request won't get logged as well.

2023-01-20 18:15 UTC, esthervillars approved these changes

2023-01-20 18:27 UTC, merged